server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: InterviewAgent
  datasource:
    url: jdbc:postgresql://192.168.100.104:5432/ai_agent_code
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  ai:
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        initialize-schema: true
  profiles:
    active: local
  data:
    redis:
      host: 192.168.100.104
      port: 6379
      database: 0
      password: xgw18720322169.
      lettuce:
        pool:
          max-active: 8
          min-idle: 0

rag:
  autoLoad: true
  batchSize: 1

logging:
  level:
    web: debug